"""baseline schema

Revision ID: 3884ec28fea9
Revises: 
Create Date: 2026-05-12 22:46:55.457008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3884ec28fea9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_external_id', sa.String(length=128), nullable=True),
    sa.Column('name_cipher', sa.Text(), nullable=False),
    sa.Column('phone_cipher', sa.Text(), nullable=True),
    sa.Column('email_cipher', sa.Text(), nullable=True),
    sa.Column('raw_file_key', sa.String(length=512), nullable=True),
    sa.Column('parsed_markdown', sa.Text(), nullable=True),
    sa.Column('extracted_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pii_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_pii_hash'), 'candidates', ['pii_hash'], unique=True)
    op.create_index('ix_candidates_source_external', 'candidates', ['source', 'source_external_id'], unique=False)
    op.create_index(op.f('ix_candidates_source_external_id'), 'candidates', ['source_external_id'], unique=False)
    op.create_table('jds',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('active_rule_version_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['active_rule_version_id'], ['rule_versions.id'], name='fk_jd_active_rule', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jds_code'), 'jds', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dingtalk_userid', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_dingtalk_userid'), 'users', ['dingtalk_userid'], unique=True)
    op.create_table('candidate_embeddings',
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.execute(
        "CREATE INDEX ix_candidate_embeddings_hnsw "
        "ON candidate_embeddings USING hnsw (embedding vector_cosine_ops) "
        "WITH (m = 16, ef_construction = 64)"
    )
    op.create_table('golden_set',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('jd_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('imported_by_user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['imported_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['jd_id'], ['jds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'jd_id', name='uq_golden_set_cand_jd')
    )
    op.create_table('rule_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('jd_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('golden_set_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['jd_id'], ['jds.id'], ),
    sa.ForeignKeyConstraint(['published_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_versions_jd_id'), 'rule_versions', ['jd_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_version_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_event_created', 'audit_logs', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('jd_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_version_id', sa.BigInteger(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('grade', sa.String(length=16), nullable=False),
    sa.Column('hard_filter_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('judge_dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cross_engine_diff', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('llm_model_main', sa.String(length=64), nullable=True),
    sa.Column('llm_model_extract', sa.String(length=64), nullable=True),
    sa.Column('cost_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_cny', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['jd_id'], ['jds.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_candidate_id'), 'scores', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_scores_jd_id'), 'scores', ['jd_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('score_id', sa.BigInteger(), nullable=False),
    sa.Column('reviewer_user_id', sa.BigInteger(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ai_agreed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['score_id'], ['scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_score_id'), 'feedback', ['score_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop the deferred FK that creates a cycle between jds and rule_versions first.
    # Use IF EXISTS because some Alembic versions don't emit the use_alter=True FK in upgrade.
    op.execute("ALTER TABLE jds DROP CONSTRAINT IF EXISTS fk_jd_active_rule")
    op.execute("DROP INDEX IF EXISTS ix_candidate_embeddings_hnsw")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_score_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_scores_jd_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_candidate_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index('ix_audit_event_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_rule_versions_jd_id'), table_name='rule_versions')
    op.drop_table('rule_versions')
    op.drop_table('golden_set')
    op.drop_table('candidate_embeddings')
    op.drop_index(op.f('ix_users_dingtalk_userid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_jds_code'), table_name='jds')
    op.drop_table('jds')
    op.drop_index(op.f('ix_candidates_source_external_id'), table_name='candidates')
    op.drop_index('ix_candidates_source_external', table_name='candidates')
    op.drop_index(op.f('ix_candidates_pii_hash'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
